services:
  database:
    image: mariadb:10.7.1
    ports:
      - 6306:6306
    environment:
      - MARIADB_USER=alexkn
      - MARIADB_PASSWORD=Grifsdar5
      - MARIADB_ROOT_PASSWORD=password123
    restart: unless-stopped
    volumes:
      - mariadata:/var/lib/mysql

volumes:
  mariadata:
